Controllers and views added
mate-academy/jv-web-practice pull request #391
Opened 2022-11-12 17:01 UTC by Pavlo-Gook

2022-11-12 17:17 UTC, CyberDogFK requested changes

2022-11-12 17:17 UTC, CyberDogFK commented on src/main/webapp/web.xml
> +        <url-pattern>/drivers/create</url-pattern>
<img width="430" alt="image" src="https://user-images.githubusercontent.com/95774539/201486155-9c13ebea-63c4-4156-99e9-55568006ada3.png">
Change url-s according to common mistakes

2022-11-12 17:24 UTC, CyberDogFK approved these changes
Looks good

2022-11-14 13:09 UTC, ChumakAn approved these changes
Looks goot to me

2022-11-14 13:09 UTC, ChumakAn commented on src/main/java/mate/controller/AddDriverToCarController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/drivers/addDriverToCar.jsp")
could be a constant

2024-12-15 15:07 UTC, closed without merging